### ISSUE TITLE
Deprecated API call needs to be replaced

### ISSUE THREAD

**Issue by pierre-ernst** [elastic/snyk-github-issue-creator#16]
[This line of code](https://github.com/elastic/snyk-github-issue-creator/blob/main/cli/snyk.js#L56) is relying on a [deprecated API](https://snyk.docs.apiary.io/#reference/projects/project-issues/list-all-issues-deprecated) that is going to be removed  on 2021-06-30.
/CC @watson @jportner

**Comment by watson** [comment]
I'm working on updating the code. So far I ran into a problem in which the new API doesn't seem to include anything similar to the `from` array that is present in the old API. Just noting it down here to back up my brain:

![image](https://user-images.githubusercontent.com/10602/120302399-271a0400-c2ce-11eb-8cf6-aaa933e2d45e.png)

We use that information for sorting and generating the dependency graph shown in the GitHub issues and in the CLI.

~~The only thing that _sounds_ like this in the new API is the `introducedThrough` array - but the content looks wrong, so I don't think it's that:~~

![image](https://user-images.githubusercontent.com/10602/120304430-1074ac80-c2d0-11eb-9dfd-cfaa7ef28f03.png)

_Update: `introducedThrough` doesn't contain the same information._

**Comment by watson** [comment]
Just had a call with Snyk about the missing information in the new endpoint:

They are aware that "path" information isn't currently available and will not remove the old API endpoint before it's possible for us to get the path by other means. However, this information will most likely not be included in the "Aggregated Issues" endpoint, but will require one or more additional API requests.
