### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by pierre-ernst** [elastic/snyk-github-issue-creator#3]
@watson suggested to publish the project to npm.
If so, it would be possible to run this using `npx`:

```
npx snyk-github-issue-creator
```

i.e. no more cloning, npm-installing and linking

**Comment by watson** [comment]
Do we want to publish under just `snyk-github-issue-creator` or `@elastic/snyk-github-issue-creator`?

**Comment by pierre-ernst** [comment]
My vote goes to `@elastic/snyk-github-issue-creator`

**Comment by watson** [comment]
Done: https://www.npmjs.com/package/@elastic/snyk-github-issue-creator
